# Generated by Django 4.2 on 2026-06-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0012_remove_chatbotconversation_response_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("manager", "Manager"), ("employee", "Employee")],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("verify", "Verify"),
                            ("transfer", "Transfer"),
                            ("return", "Return"),
                            ("assign", "Assign"),
                            ("import", "Import"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("status_change", "Status Change"),
                            ("password_change", "Password Change"),
                            ("profile_update", "Profile Update"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "related_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("related_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["user", "timestamp"], name="hardware_ma_user_id_57fd46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["user_type", "timestamp"], name="hardware_ma_user_ty_ea5463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["action", "timestamp"], name="hardware_ma_action_58dd9a_idx"
            ),
        ),
    ]
