# Generated by Django 4.2 on 2026-06-09 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0013_logentry_logentry_hardware_ma_user_id_57fd46_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareBackupChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_priority",
                    models.IntegerField(
                        choices=[(1, "Primary"), (2, "Secondary"), (3, "Tertiary")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_backup_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_handler",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_handled_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hardware_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_chains",
                        to="hardware_management.hardwareassignment",
                    ),
                ),
                (
                    "primary_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_backup_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondary_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_backup_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tertiary_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tertiary_backup_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("hardware_assignment", "primary_employee")},
            },
        ),
        migrations.CreateModel(
            name="HardwareBackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("activated", "Backup Activated"),
                            ("deactivated", "Backup Deactivated"),
                            ("handover", "Handover Completed"),
                            ("escalated", "Escalated to Next Backup"),
                            ("returned", "Returned to Primary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "backup_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="hardware_management.hardwarebackupchain",
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackupAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
    ]
