# Generated by Django 4.2 on 2026-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0015_handoverrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handoverrequest",
            name="backup_chain",
        ),
        migrations.RemoveField(
            model_name="handoverrequest",
            name="from_employee",
        ),
        migrations.RemoveField(
            model_name="handoverrequest",
            name="responded_by",
        ),
        migrations.RemoveField(
            model_name="handoverrequest",
            name="to_employee",
        ),
        migrations.AlterUniqueTogether(
            name="hardwarebackupchain",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="current_handler",
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="hardware_assignment",
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="primary_employee",
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="secondary_employee",
        ),
        migrations.RemoveField(
            model_name="hardwarebackupchain",
            name="tertiary_employee",
        ),
        migrations.RemoveField(
            model_name="hardwarebackuplog",
            name="backup_chain",
        ),
        migrations.RemoveField(
            model_name="hardwarebackuplog",
            name="from_employee",
        ),
        migrations.RemoveField(
            model_name="hardwarebackuplog",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="hardwarebackuplog",
            name="to_employee",
        ),
        migrations.AddField(
            model_name="logentry",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="previous_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="request_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("create", "Create"),
                    ("edit", "Edit"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("verify", "Verify"),
                    ("transfer", "Transfer"),
                    ("return", "Return"),
                    ("assign", "Assign"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("handover", "Handover"),
                    ("status_change", "Status Change"),
                    ("password_change", "Password Change"),
                    ("profile_update", "Profile Update"),
                    ("search", "Search"),
                    ("filter", "Filter"),
                    ("click", "Button Click"),
                    ("download", "Download"),
                    ("upload", "Upload"),
                    ("submit", "Submit"),
                    ("cancel", "Cancel"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="BackupAvailability",
        ),
        migrations.DeleteModel(
            name="HandoverRequest",
        ),
        migrations.DeleteModel(
            name="HardwareBackupChain",
        ),
        migrations.DeleteModel(
            name="HardwareBackupLog",
        ),
    ]
