# Generated by Django 4.2 on 2026-06-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0016_remove_handoverrequest_backup_chain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="branch_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="LogEntry",
        ),
    ]
