# Generated by Django 4.2 on 2026-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0017_customuser_branch_location_delete_logentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
    ]
