# Generated by Django 4.2 on 2026-06-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0018_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("manager", "Manager"), ("employee", "Employee")],
                max_length=20,
            ),
        ),
    ]
