# Generated by Django 4.2 on 2026-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0019_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="asset_number",
            field=models.CharField(
                blank=True,
                help_text="Unique asset tag number",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
