# Generated by Django 4.2 on 2026-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0021_hardwareassetentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareassignment",
            name="exam_center_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the exam center",
                max_length=200,
                null=True,
            ),
        ),
    ]
