# Generated by Django 4.2 on 2026-06-28 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0022_hardwareassignment_exam_center_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeehardwaretransfer",
            old_name="approved_date",
            new_name="approved_by_receiver_date",
        ),
        migrations.RenameField(
            model_name="employeehardwaretransfer",
            old_name="manager_notes",
            new_name="receiver_manager_notes",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="approved_by_receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="approved_by_sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="approved_by_sender_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="from_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="sender_manager_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="to_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_by_sender_manager", "Approved by Sender Manager"),
                    ("approved_by_receiver_manager", "Approved by Receiver Manager"),
                    ("in_transit", "In Transit"),
                    ("received_by_receiver", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_by_sender_manager", "Approved by Sender Manager"),
                    ("approved_by_receiver_manager", "Approved by Receiver Manager"),
                    ("in_transit", "In Transit"),
                    ("received_by_receiver", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
