# Generated by Django 4.2 on 2026-06-28 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0023_rename_approved_date_employeehardwaretransfer_approved_by_receiver_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeehardwaretransfer",
            old_name="approved_by_receiver_date",
            new_name="approved_date",
        ),
        migrations.RenameField(
            model_name="employeehardwaretransfer",
            old_name="receiver_manager_notes",
            new_name="manager_notes",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="approved_by_receiver",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="approved_by_sender",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="approved_by_sender_date",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="from_branch",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="sender_manager_notes",
        ),
        migrations.RemoveField(
            model_name="employeehardwaretransfer",
            name="to_branch",
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved_emp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_by_manager", "Approved by Manager"),
                    ("in_transit", "In Transit"),
                    ("received_by_receiver", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_by_manager", "Approved by Manager"),
                    ("in_transit", "In Transit"),
                    ("received_by_receiver", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
