# Generated by Django 4.2 on 2026-06-28 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0025_alter_employeehardwaretransfer_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved_emp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
