# Generated by Django 4.2 on 2026-06-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0026_alter_employeehardwaretransfer_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
