# Generated by Django 4.2 on 2026-07-06 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0027_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
