# Generated by Django 4.2 on 2026-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0028_project_assigned_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="to_exam_center",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
