# Generated by Django 4.2 on 2026-07-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0030_assignmentdraft"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssignmentDraft",
        ),
    ]
