# Generated by Django 4.2 on 2026-07-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0032_hardwarerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwarerequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
