# Generated by Django 4.2 on 2026-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0034_alter_project_options_project_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Optional: Reference location only - project is available to ALL managers",
                max_length=100,
                null=True,
            ),
        ),
    ]
