# Generated by Django 4.2 on 2026-07-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0035_alter_project_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hardware",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="hardware",
            name="employee",
        ),
        migrations.AddField(
            model_name="hardware",
            name="assigned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hardware",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_hardware",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hardware",
            name="branch_location",
            field=models.CharField(
                blank=True,
                help_text="Branch where hardware is located",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hardware",
            name="expected_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hardware",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_hardware",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="hardware_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hardware_items",
                to="hardware_management.hardwaretype",
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="model_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="hardware",
            index=models.Index(
                fields=["asset_number"], name="hardware_ma_asset_n_c3496c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardware",
            index=models.Index(
                fields=["serial_number"], name="hardware_ma_serial__999784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardware",
            index=models.Index(fields=["status"], name="hardware_ma_status_e91609_idx"),
        ),
        migrations.AddIndex(
            model_name="hardware",
            index=models.Index(
                fields=["branch_location"], name="hardware_ma_branch__6651c3_idx"
            ),
        ),
    ]
