# Generated by Django 4.2 on 2026-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0038_employeeupdaterequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hardwaretype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="hardwaretype",
            name="icon",
            field=models.CharField(
                blank=True, default="laptop", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hardwaretype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
