# Generated by Django 4.2 on 2026-07-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0040_message_messagenotification_messageattachment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageattachment",
            name="message",
        ),
        migrations.RemoveField(
            model_name="messagenotification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="messagenotification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="MessageAttachment",
        ),
        migrations.DeleteModel(
            name="MessageNotification",
        ),
    ]
