# Generated by Django 4.2 on 2026-07-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0041_remove_messageattachment_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferhistory",
            name="transfer",
        ),
        migrations.RemoveField(
            model_name="transferhistory",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="transferitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="transferitem",
            name="hardware",
        ),
        migrations.RemoveField(
            model_name="transferitem",
            name="transfer",
        ),
        migrations.RemoveField(
            model_name="transfernotification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="transfernotification",
            name="transfer",
        ),
        migrations.DeleteModel(
            name="EmployeeHardwareTransfer",
        ),
        migrations.DeleteModel(
            name="TransferHistory",
        ),
        migrations.DeleteModel(
            name="TransferItem",
        ),
        migrations.DeleteModel(
            name="TransferNotification",
        ),
    ]
