# Generated by Django 4.2 on 2026-07-31 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0044_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="old_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("failed_login", "Failed Login"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_request", "Password Reset Request"),
                    ("user_create", "Create User"),
                    ("user_update", "Update User"),
                    ("user_delete", "Delete User"),
                    ("user_bulk_create", "Bulk Create Users"),
                    ("user_activate", "Activate User"),
                    ("user_deactivate", "Deactivate User"),
                    ("user_type_change", "Change User Type"),
                    ("employee_create", "Create Employee"),
                    ("employee_update", "Update Employee"),
                    ("employee_delete", "Delete Employee"),
                    ("employee_bulk_create", "Bulk Create Employees"),
                    ("employee_request_delete", "Request Employee Delete"),
                    ("employee_request_update", "Request Employee Update"),
                    ("employee_approve_delete", "Approve Employee Delete"),
                    ("employee_reject_delete", "Reject Employee Delete"),
                    ("employee_approve_update", "Approve Employee Update"),
                    ("employee_reject_update", "Reject Employee Update"),
                    ("hardware_create", "Create Hardware"),
                    ("hardware_update", "Update Hardware"),
                    ("hardware_delete", "Delete Hardware"),
                    ("hardware_bulk_create", "Bulk Create Hardware"),
                    ("hardware_status_change", "Change Hardware Status"),
                    ("hardware_request_update", "Request Hardware Update"),
                    ("hardware_request_delete", "Request Hardware Delete"),
                    ("hardware_approve_update", "Approve Hardware Update"),
                    ("hardware_reject_update", "Reject Hardware Update"),
                    ("hardware_approve_delete", "Approve Hardware Delete"),
                    ("hardware_reject_delete", "Reject Hardware Delete"),
                    ("hardware_type_create", "Create Hardware Type"),
                    ("hardware_type_update", "Update Hardware Type"),
                    ("hardware_type_delete", "Delete Hardware Type"),
                    ("assignment_create", "Create Assignment"),
                    ("assignment_update", "Update Assignment"),
                    ("assignment_return", "Return Assignment"),
                    ("assignment_auto_return", "Auto Return Assignment"),
                    ("assignment_item_add", "Add Hardware to Assignment"),
                    ("assignment_item_remove", "Remove Hardware from Assignment"),
                    (
                        "assignment_item_remove_all",
                        "Remove All Hardware from Assignment",
                    ),
                    ("asset_entry", "Asset Number Entry"),
                    ("asset_entry_update", "Asset Number Update"),
                    ("asset_verify", "Verify Asset"),
                    ("asset_verify_all", "Verify All Assets"),
                    ("asset_entry_remove", "Remove Asset Entry"),
                    ("transfer_request", "Request Transfer"),
                    ("transfer_approve", "Approve Transfer"),
                    ("transfer_reject", "Reject Transfer"),
                    ("transfer_complete", "Complete Transfer"),
                    ("transfer_return", "Return Transfer"),
                    ("transfer_cancel", "Cancel Transfer"),
                    ("transfer_status_update", "Update Transfer Status"),
                    ("project_create", "Create Project"),
                    ("project_update", "Update Project"),
                    ("project_delete", "Delete Project"),
                    ("project_archive", "Archive Project"),
                    ("project_export", "Export Project"),
                    ("export_report", "Export Report"),
                    ("export_assignments", "Export Assignments"),
                    ("export_hardware", "Export Hardware"),
                    ("chatbot_query", "Chatbot Query"),
                    ("system_error", "System Error"),
                    ("system_warning", "System Warning"),
                    ("system_info", "System Info"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="hardware_ma_created_fdf9e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "action"], name="hardware_ma_user_id_261c1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["role", "action"], name="hardware_ma_role_ce9de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_model", "target_id"],
                name="hardware_ma_target__da242f_idx",
            ),
        ),
    ]
