# Generated by Django 4.2 on 2026-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0045_auditlog_new_value_auditlog_old_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address"], name="hardware_ma_ip_addr_fd5919_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["created_at"], name="hardware_ma_created_00f4b0_idx"
            ),
        ),
    ]
