# Generated by Django 4.2 on 2026-08-04 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0046_auditlog_session_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="approved_by_super_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="super_admin_approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="from_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="is_cross_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="rejected_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="super_admin_approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeehardwaretransfer",
            name="to_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manager", "Manager Approval"),
                    ("super_admin", "Super Admin Approval"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="is_cross_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transferitem",
            name="from_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transferitem",
            name="is_cross_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transferitem",
            name="to_branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transfernotification",
            name="is_cross_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transfernotification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("request_created", "Transfer Request Created"),
                    ("manager_approval", "Manager Approval Required"),
                    ("super_admin_approval", "Super Admin Approval Required"),
                    ("approved", "Transfer Approved"),
                    ("rejected", "Transfer Rejected"),
                    ("in_transit", "Transfer In Transit"),
                    ("received", "Transfer Received"),
                    ("completed", "Transfer Completed"),
                    ("returned", "Transfer Returned"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved_emp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_mgr", "Approved by Manager"),
                    ("approved_sa", "Approved by Super Admin"),
                    ("in_transit", "In Transit"),
                    ("received", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_mgr", "Approved by Manager"),
                    ("approved_sa", "Approved by Super Admin"),
                    ("in_transit", "In Transit"),
                    ("received", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
