# Generated by Django 4.2 on 2026-08-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0047_employeehardwaretransfer_approved_by_super_admin_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeehardwaretransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Transfer Requested"),
                    ("approved_mgr", "Approved by Manager"),
                    ("approved_sa", "Approved by Super Admin"),
                    ("in_transit", "In Transit"),
                    ("received", "Received by Receiver"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=100,
            ),
        ),
    ]
