# Generated by Django 4.2 on 2026-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0048_alter_employeehardwaretransfer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="hardware_location",
            field=models.CharField(
                blank=True,
                help_text="Current physical location of the hardware",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="branch_location",
            field=models.CharField(
                blank=True,
                help_text="Parent branch where hardware belongs",
                max_length=100,
                null=True,
            ),
        ),
    ]
