# Generated by Django 4.2 on 2026-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0051_assignmentdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareassignmentitem",
            name="returned_asset_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hardwareassignmentitem",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
