# Generated by Django 4.2 on 2026-08-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hardware_management",
            "0052_hardwareassignmentitem_returned_asset_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_first_login",
        ),
    ]
