# Generated by Django 4.2 on 2026-08-13 10:33
import uuid
from django.db import migrations, models

def generate_unique_hardware_ids(apps, schema_editor):
    """
    Generate a unique UUID for every existing row in the Hardware table.
    """
    Hardware = apps.get_model('hardware_management', 'Hardware')
    for hardware in Hardware.objects.all():
        hardware.hardware_id = uuid.uuid4()
        hardware.save(update_fields=['hardware_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('hardware_management', '0053_remove_customuser_is_first_login'),
    ]

    operations = [
        # Step 1: Add the field with null=True, blank=True, and without unique=True
        migrations.AddField(
            model_name='hardware',
            name='hardware_id',
            field=models.UUIDField(
                default=uuid.uuid4, 
                null=True, 
                blank=True,
                db_index=True
            ),
        ),
        
        # Step 2: Generate a unique UUID for all existing rows
        migrations.RunPython(
            generate_unique_hardware_ids,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Step 3: Alter the field to make it unique, non-nullable, and non-editable
        migrations.AlterField(
            model_name='hardware',
            name='hardware_id',
            field=models.UUIDField(
                default=uuid.uuid4, 
                unique=True, 
                editable=False,
                db_index=True
            ),
        ),
    ]