# Generated by Django 4.2 on 2026-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0054_hardware_hardware_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_change_locked",
            field=models.BooleanField(
                default=False,
                help_text="If True, the employee cannot change their own password. Only Super Admin can unlock it.",
            ),
        ),
    ]
