# Generated by Django 4.2 on 2026-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_management", "0055_customuser_password_change_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
